# Generated by Django 5.0.7 on 2024-07-18 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='quantity',
        ),
    ]
