# Generated by Django 5.0.7 on 2024-07-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0009_remove_stock_stock_order_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='stock',
        ),
        migrations.AddField(
            model_name='order',
            name='stock',
            field=models.ManyToManyField(to='warehouse.stock'),
        ),
    ]
