# Generated by Django 5.0.7 on 2024-07-19 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0011_remove_order_stock_order_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('shipped', 'shipped')], max_length=50),
        ),
    ]
